### PR TITLE
install docker-engine from new repo

### PR DESCRIPTION
**Pull request by vincentfretin**
The installation of docker failed because of lack of https support.
http://get.docker.io/ubuntu now redirects to https.
You need apt-transport-https so apt-get supports https repositories, and you need to install it before adding a https repo.
Now install docker-engine from the new repo, see blog.docker.com/2015/07/new-apt-and-yum-repos/

### CODE REVIEW

**Comment by mafr** [comment]
Thank you for the PR - I'll have a closer look later next week when I get my dev box fixed. However, I'm pretty sure that ubuntu-security-repo is actually used.

**Comment by vincentfretin** [comment]
It's not actually used, see https://github.com/mafr/docker-update-check/blob/master/update-check#L3  and https://github.com/mafr/docker-update-check/blob/master/update-check#L28
I guess you had a permission issue with the volume because you used ubuntu:14.04 for check image and busybox on repo image. See http://container42.com/2014/11/18/data-only-container-madness/

**Comment by vincentfretin** [comment]
Thanks for the code btw!

**Comment by mafr** [comment]
Thank you :)

**Pull request merged**
